# Stage 1: Build dependencies
FROM python:3.11-slim AS builder

# Install system dependencies for building Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry (2.x to match poetry.lock generated by Poetry 2.1.4)
ENV POETRY_VERSION=2.1.4
ENV POETRY_HOME=/opt/poetry
ENV POETRY_CACHE_DIR=/opt/poetry-cache
RUN curl -sSL https://install.python-poetry.org | python3 - --version 2.1.4 && \
    chmod +x /opt/poetry/bin/poetry

# Set working directory
WORKDIR /app

# Copy dependency files
COPY pyproject.toml poetry.lock ./

# Configure Poetry: Don't create virtual env, install to system
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VENV_IN_PROJECT=1 \
    POETRY_CACHE_DIR=/opt/poetry-cache

# Regenerate lock file if pyproject.toml changed (evita erro "Run poetry lock to fix the lock file")
RUN /opt/poetry/bin/poetry lock

# Install dependencies
RUN /opt/poetry/bin/poetry install --only main --no-root

# Poetry 2 cria o venv no cache; copiar para /app/.venv para o stage 2
RUN VENV_PATH=$(/opt/poetry/bin/poetry env info -p) && cp -a "$VENV_PATH" /app/.venv

# Stage 2: Runtime
FROM python:3.11-slim

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy Poetry from builder
ENV POETRY_HOME=/opt/poetry
COPY --from=builder /opt/poetry /opt/poetry
ENV PATH="$POETRY_HOME/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy installed dependencies from builder
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

# Copy application code
COPY . .

# Create non-root user for security
RUN useradd -m -u 1000 appuser && \
    chown -R appuser:appuser /app
USER appuser

# Expose port (Coolify will set PORT env var)
ENV PORT=8000
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:${PORT:-8000}/health || exit 1

# Run the application
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
